# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herm < Formula
  desc "A containerized coding agent CLI"
  homepage "https://github.com/aduermael/herm"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aduermael/herm/releases/download/v0.3.0/herm_0.3.0_darwin_amd64.tar.gz"
      sha256 "172596ef53cf41b2ca199fa8e35b759ade9bbe95624831839bf06da15cdd1d4c"

      define_method(:install) do
        bin.install "herm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aduermael/herm/releases/download/v0.3.0/herm_0.3.0_darwin_arm64.tar.gz"
      sha256 "0dda0bacf62b05fb47972d962a3fa8583b87e5b1d7650999309e3a35ec84041f"

      define_method(:install) do
        bin.install "herm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aduermael/herm/releases/download/v0.3.0/herm_0.3.0_linux_amd64.tar.gz"
      sha256 "da518dbf203498ac140ec2aacd49dc201b87a086cb1b9c443cbcb5fc35eeb9cc"
      define_method(:install) do
        bin.install "herm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aduermael/herm/releases/download/v0.3.0/herm_0.3.0_linux_arm64.tar.gz"
      sha256 "9001187c26ef26edc668b15d3f954cc1429697f8702e6455e707f0f96879de7f"
      define_method(:install) do
        bin.install "herm"
      end
    end
  end

  test do
    system "#{bin}/herm", "--help"
  end
end
