# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herm < Formula
  desc "A containerized coding agent CLI"
  homepage "https://github.com/aduermael/herm"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aduermael/herm/releases/download/v0.8.2/herm_0.8.2_darwin_amd64.tar.gz"
      sha256 "baa7504824cd5c21df16f71d1eb15f370e3e1b28c174df4155639fec1c6ec890"

      define_method(:install) do
        bin.install "herm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aduermael/herm/releases/download/v0.8.2/herm_0.8.2_darwin_arm64.tar.gz"
      sha256 "3ab7c872f4168195cea1708cf7d90ae2fcbb618435c0925be50259204d8647f1"

      define_method(:install) do
        bin.install "herm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aduermael/herm/releases/download/v0.8.2/herm_0.8.2_linux_amd64.tar.gz"
      sha256 "b03d765228acb9d6f4859905aa76b383c658427e703b52414384bd51547cf42a"
      define_method(:install) do
        bin.install "herm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aduermael/herm/releases/download/v0.8.2/herm_0.8.2_linux_arm64.tar.gz"
      sha256 "164048f5d1fb1a434b038ab2873c4f96cf0493c0fd4f7fff37d654742de9c821"
      define_method(:install) do
        bin.install "herm"
      end
    end
  end

  test do
    system "#{bin}/herm", "--help"
  end
end
