# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herm < Formula
  desc "A containerized coding agent CLI"
  homepage "https://github.com/aduermael/herm"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aduermael/herm/releases/download/v0.5.0/herm_0.5.0_darwin_amd64.tar.gz"
      sha256 "4bec2f567739c43e801b807d213d27847898dc1a11d83d32ad9219daf3e805aa"

      define_method(:install) do
        bin.install "herm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aduermael/herm/releases/download/v0.5.0/herm_0.5.0_darwin_arm64.tar.gz"
      sha256 "e7d01f921d4fd6df07809391e21dc8a137eb146a34a0970b12defb76f2f1eb7d"

      define_method(:install) do
        bin.install "herm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aduermael/herm/releases/download/v0.5.0/herm_0.5.0_linux_amd64.tar.gz"
      sha256 "5f26f48658fbc1ab038579387d80d5a146968bf2de547727df315db4d0888ac1"
      define_method(:install) do
        bin.install "herm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aduermael/herm/releases/download/v0.5.0/herm_0.5.0_linux_arm64.tar.gz"
      sha256 "ade457625f20bdee1053ff5c9c1ad78f4e6711f8e6453a3164c9ce170c52052e"
      define_method(:install) do
        bin.install "herm"
      end
    end
  end

  test do
    system "#{bin}/herm", "--help"
  end
end
